# Generated by Django 4.2.3 on 2023-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
