# Generated by Django 4.2.3 on 2023-08-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_match_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
    ]
