# Generated by Django 4.2.3 on 2023-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_match_phase_name_alter_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_extra_time_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_penalty_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_extra_time_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_penalty_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
