# Generated by Django 4.2.3 on 2023-08-21 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_match_team1_extra_time_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_teams_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
